// <auto-generated />
namespace EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Table : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205290622462_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9NnH6XHZZFRz6/z8vw90dh5CDQ+sh1QF6eESnv95nqVczeffXQ8WxRLvwk1+r3y6+AD+uhlXa3yur1+lZ/ri2dPP0rvhu/d7b5oX/PeQd/027K9t/dR+mJdltmkpA/Os7LJP0pXnz563VZ1/nm+zOuszWcvs7bNa5qFs1nOuCsNHq0+vR0ZHt7d2QMZ7mbLZdVmLU1pD/EOmq+vmzZfvKbG68Yg/OS6zX1823qd3wTneXVBtFUAr9ua2Oyj9FnxLp89z5cX7dyO+ovsnfmEfv0o/WpZEFfaXt6v15dXs5/lPh/fdWy0kbm+avL6R7z1s8db+PU953p3b8NUa/Nb9Pz+TPbhHf+cjPZ0kRXle/b6zcoT2Ys2K4hlFSP8nb9rO3IlbV/nbaDXUwdYLMhYP+8Muvs2C27/Zfk4hrpF0lmzu2LOjNm7O2D3Hn+RrVZEVc8O6ifpazGCJ9uv39/wLQTG3WkTsX8WW9sT6YXsIu98C1rP8mdF3bRPszabZJjnk9ki0mzjlJheBi1uoDtNa/yuPPhMp63zkiPVM8J+QTqMB6LDoI4HOuM3X0+zMqsjSvSkKteLpfs7ZJVNb4e6zYcTfnN7iGpBfVD60e1hsKryIfAH/fcf3+0QsztFnpRqy46J6k74rdihbyNv5obYO7dghvhr/5/iBbEBPX6Qj98TVo8x3Ke3h9RH6H1xUQvjg9CPfsg82tPl3Sa2d6vTO7r7serRmwObnmKVJh+lRJzLYgalKnwyRoPx619UnpQFjdc1+CJbFud5076p3uYI0kjvf/1YyTpyTTMr/18ZMBUY+43u63s6NzFntC2W19zZ1/BHDYzlZVZP51m9tcje3XlfSJ5r+R5w/l8ek/x/YvpEc4Wk77nT74ljN1r4puD+bOAa+PrfGO/1/feuTxki1fXFb/DkRXF+9tFsUhHqguI34OTHwH6Q+983DY/v+pmxx0/zprhwIJAnW+ZTxNQOqGlztjyvzOTRgHyMTJPO3H6Rt9mMCH5ct8V5Nm3p62neNBzO/WRWrnn6J/nsbPnlul2t2+OmyReT8tof7+O7m/vnGCfE+fGXK/zl2cKvPwRCs6Ah5F8un6yLcmbxftbn7SEQ4D1VQIQVhbME7uLaQnpRLW8JSMn3NF/lS6ivN/liVRKw5svl6+wyH8btZhqGFHv8tMgu6mzhU1A+MUowo569LqgD/w3XH/1J7Epp2aP/JwAA//90gK4rCxYAAA=="; }
        }
    }
}
